blog/urls.py
from django.urls import path
from .views import home, photo_upload, photo_and_blog_upload, view_blog, edit_blog, create_multiple_photos, follow_users
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('blog/', home, name='home'),
    path('photo/telecharger/', photo_upload, name='photo_upload'),
    path('photo/upload-multiple/', create_multiple_photos, name='create_upload_multiple'),
    path('blog/create/', photo_and_blog_upload, name='blog_post'),
    path('blog/<int:blog_id>/', view_blog, name='view_blog'),
    path('blog/<int:blog_id>/edit/', edit_blog, name='edit_blog'),
    path('follow-users/', follow_users, name='follow_users'),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentification.urls')),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.conf import settings
from PIL import Image

class Photo(models.Model):
    image = models.ImageField()
    caption = models.CharField(max_length=200, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    # cette clase permet de spécifier des permissions beaucoup plus fines
    class Meta:
        permissions = [
            ('change_blog_title', 'Peut changer le titre d\'un billet')
        ]

    def __str__(self) -> str:
        return self.caption

    IMAGE_MAX_SIZE = (800, 800)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()
        
class Blog(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=5000)
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    word_count = models.IntegerField(null=True, blank=True)

    def __str__(self) -> str:
        return self.title

    def _get_word_count(self):
        return len(self.content.split(' '))
    
    def save(self, *args, **kwargs):
        self.word_count = self._get_word_count()
        super().save(*args, **kwargs)
        
class BlogContributor(models.Model):
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)

    class Meta:
        """
        Nous avons défini l'attribut   unique_together  dans la classe   Meta  pour garantir 
        qu'il n'y a qu'une seule instance de  BlogContributor  pour chaque paire   
        contributor  -   blog
        """
        unique_together = ('contributor', 'blog')

blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Photo, Blog

User = get_user_model()

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image', 'caption']

class BlogForm(forms.ModelForm):
    edit_blog = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    class Meta:
        model = Blog
        fields = ['title', 'content', 'word_count', 'contributors']

class DeleteBlogForm(forms.Form):
    delete_blog = forms.BooleanField(widget=forms.HiddenInput, initial=True)


class FollowUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['follows']

blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.forms import formset_factory
from django.db.models import Q
from .forms import PhotoForm, BlogForm, DeleteBlogForm, FollowUserForm
from .models import Photo, Blog

@login_required
@permission_required('blog.add_photo', raise_exception=True)
def photo_upload(request):
    form = PhotoForm()
    if request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)
        photo = form.save(commit=False)
        photo.uploader = request.user
        photo.save()
        return redirect('blog:home')


    return render(request, 'blog/photo_upload.html', context={'form': form})

@login_required
def photo_and_blog_upload(request):
    photo_form = PhotoForm()
    blog_form = BlogForm()

    if request.method == 'POST':
        photo_form = PhotoForm(request.POST, request.FILES)
        blog_form = BlogForm(request.POST)

        if any([photo_form.is_valid(), blog_form.is_valid()]):
            photo = photo_form.save(commit=False)
            photo.uploader = request.user
            photo.save()
            blog = blog_form.save(commit=False)
            blog.author = request.user
            blog.photo = photo
            blog.save()
            # champs ManyToMany
            blog.contributors.add(request.user, through_defaults={'contribution': 'Auteur principal'})
        
            return redirect('blog:home')
        
    context = {
        'blog_form': blog_form,
        'photo_form': photo_form,
    }

    return render(request, 'blog/blog_post.html', context=context)

@login_required
def view_blog(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    return render(request, 'blog/view_blog.html', {'blog': blog})

@login_required
def edit_blog(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    edit_form = BlogForm(instance=blog)
    delete_form = DeleteBlogForm()
    if request.method == 'POST':
        if 'edit_blog' in request.POST:
            edit_form = BlogForm(request.POST, instance=blog)
            if edit_form.is_valid():
                edit_form.save()
                return redirect('blog:home')
            
        if 'delete_blog' in request.POST:
            delete_form = DeleteBlogForm(request.POST)
            if delete_form.is_valid():
                blog.delete()
                return redirect('blog:home')
    context = {
        'edit_form': edit_form,
        'delete_form': delete_form,
    }
    return render(request, 'blog/edit_blog.html', context=context)

@login_required
def home(request):
    # photos = Photo.objects.all()
    # blogs = Blog.objects.all()
    """ blogs = Blog.objects.filter(contributors__in=request.user.follows.all())
    photos = Photo.objects.filter(uploader__in=request.user.follows.all()).exclude(blog__in=blogs) """
    # on ne veut voir que les photos publié par les personnes que l'on suit
    blogs = Blog.objects.filter(
        Q(contributors__in=request.user.follows.all()) | Q(starred=True))
    photos = Photo.objects.filter(
        uploader__in=request.user.follows.all()).exclude(
            blog__in=blogs
    )


    paginator = Paginator(blogs, 3)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)

    context = {
        'page_obj': page_obj,
        'photos': photos,
    }
    return render(request, 'blog/home.html', context=context)

def create_multiple_photos(request):
    PhotoFormset = formset_factory(PhotoForm, extra=5)
    formset = PhotoFormset()
    if request.method == 'POST':
        for form in formset:
            # permet de vérifier s'il y a des données dans le formulaire
            if form.cleaned_data:
                photo = form.save(commit=False)
                photo.uploader = request.user
                photo.save()
        return redirect('blog:home')
    return render(request, 'blog/create_multiple_photos.html', context={'formset': formset})


def follow_users(request):
    form = FollowUserForm(instance=request.user)
    if request.method == 'POST':
        form = FollowUserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('blog:home')
    return render(request, 'blog/follow_users_form.html', context={'form': form})

blog/templates/blog/blog_post.html
{% extends 'base.html' %}
{% block content %}
<h2>Créer un post</h2>
<form method="post" enctype="multipart/form-data">
    {{ blog_form.as_p }}
    {{ photo_form.as_p }}
    {% csrf_token %}
    <button type="submit" >Publier</button>
</form>
{% endblock content %}

blog/templates/blog/create_multiple_photos.html
{% extends 'base.html' %}
{% block content %}
    <h2>Télécharger plusieurs photos</h2>
    <form method="post" enctype="multipart/form-data">
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form.as_p }}
        {% endfor %}
        {% csrf_token %}
        <button type="submit" >Publier</button>
    </form>
{% endblock content %}

blog/templates/blog/edit_blog.html
{% extends 'base.html' %}
{% block content %}
    <h2>Modifier le billet</h2>
    <form method="post">
        {{ edit_form.as_p }}
        {% csrf_token %}
        <button type="submit" >Sauvegarder</button>
    </form>
    <hr>
    <h3>Supprimer le billet ?</h3>
    <form method="post">
        {{ delete_form }}
        {% csrf_token %}
        <button type="submit" >Supprimer</button>
    </form>
{% endblock content %}

blog/templates/blog/follow_users_form.html
{% extends 'base.html' %}
{% block content %}
    <h2>Suivre des utilisateurs</h2>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" >Confirmer</button>
    </form>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %}
{% load blog_extras %}
{% block content %}
    <h2>Votre Flux</h2>
    <div class="grid-container">
        {% for photo in photos %}  
        <div class="post">  
            <img src="{{ photo.image.url }}"/>
            <p>{{ photo.caption }}</p>
            {% comment %} <p><strong>Prise par {{ photo.uploader }}</strong></p> {% endcomment %}
            <p><strong>Prise par {% get_poster_display photo.uploader %}</strong></p>
            <p>{{ photo.date_created|date:'d M Y' }}</p>
        </div>
        {% endfor %}

        {% for blog in page_obj %}
            <div class="post">
                <a href="{% url 'blog:view_blog' blog.id %}">
                    <h4>Billet : {{ blog.title }}</h4>
                    <img src="{{ blog.photo.image.url }}">
                    <p><strong>Ecrit par {{ blog.contributors.all|join:", "  }}</strong></p> 
                    <p>{{ blog.date_created|get_posted_at_display }}</p>
                </a>
            </div>
        {% endfor %}
    </div>

    <span>
        {% if page_obj.has_previous %}
            <a href="?page=1">« première</a>
            <a href="?page={{ page_obj.previous_page_number }}">précédente</a>
        {% endif %}
    
        <span>
            Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">suivante</a>            
            <a href="?page={{ page_obj.paginator.num_pages }}">dernière »</a>
        {% endif %}
    </span>

    {% comment %} <h2>Blog</h2>
    <div class="grid-container">
        {% for blog in blogs %}
            <div class="post">
                <a href="{% url 'blog:view_blog' blog.id %}">
                    <h4>Billet : {{ blog.title }}</h4>
                    <img src="{{ blog.photo.image.url }}">
                </a>
            </div>
        {% endfor %}
    </div> {% endcomment %}

{% endblock content %}

blog/templates/blog/photo_upload.html
{% extends 'base.html' %}
{% block content %}
<h2>Télécharger une photo</h2>
<form method="post" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" >Publier</button>
</form>
{% endblock content %}

blog/templates/blog/view_blog.html
{% extends 'base.html' %}
{% block content %}
    <h2>{{ blog.title }}</h2>
    <p><a href="{% url 'blog:edit_blog' blog.id %}">Modifier le billet</a></p>
    <img src="{{ blog.photo.image.url }}">
    <p>{{ blog.photo.caption }}</p>
    <p>{{ blog.content }}</p>
{% endblock content %}