authentification/urls.py
from django.urls import path
# cette page peut être générer sans avoir à créer une vue contenant 
# tout le processus contenue dans la vue LoginPage (cela permet de gagner du temps)
# (utilisation des vues générics)
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from .views import login_page, logout_user, LoginPage, signup_page

app_name = 'authentification'

urlpatterns = [
    # path('', LoginPage.as_view(), name='login'),
    path('', LoginView.as_view(template_name='authentification/login.html',
                               redirect_authenticated_user=True
                               ), name='login'),
    # path('logout/', logout_user , name='logout'),
    path('logout/', LogoutView.as_view(
        next_page='blog:home' # si ce paramètre n'est pas indiqué par défaut djangoi cherche dans la 
        # variable settings.LOGOUT_REDIRECT_URL (https://docs.djangoproject.com/fr/3.1/topics/auth/default/#how-to-log-a-user-out)
    ) , name='logout'),

    path('password_change/', PasswordChangeView.as_view(
        template_name='authentification/password_change.html', # si ce paramètre n'est pas indiqué par défaut 
        # django cherche dans le dossier  registration/password_change_form.html 
        # (https://docs.djangoproject.com/fr/3.1/topics/auth/default/#how-to-log-a-user-out)
        success_url = 'blog:home',
    ) , name='password_change'),

    path('signup/', signup_page, name='signup'),

]

blog/urls.py
from django.urls import path
from .views import home, photo_upload, photo_and_blog_upload, view_blog, edit_blog, create_multiple_photos, follow_users
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    path('blog/', home, name='home'),
    path('photo/telecharger/', photo_upload, name='photo_upload'),
    path('photo/upload-multiple/', create_multiple_photos, name='create_upload_multiple'),
    path('blog/create/', photo_and_blog_upload, name='blog_post'),
    path('blog/<int:blog_id>/', view_blog, name='view_blog'),
    path('blog/<int:blog_id>/edit/', edit_blog, name='edit_blog'),
    path('follow-users/', follow_users, name='follow_users'),
    
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentification.urls')),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.conf import settings
from PIL import Image

class Photo(models.Model):
    image = models.ImageField()
    caption = models.CharField(max_length=200, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    # cette clase permet de spécifier des permissions beaucoup plus fines
    class Meta:
        permissions = [
            ('change_blog_title', 'Peut changer le titre d\'un billet')
        ]

    def __str__(self) -> str:
        return self.caption

    IMAGE_MAX_SIZE = (800, 800)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()
        
class Blog(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=200)
    content = models.TextField(max_length=5000)
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    word_count = models.IntegerField(null=True, blank=True)

    def __str__(self) -> str:
        return self.title

    def _get_word_count(self):
        return len(self.content.split(' '))
    
    def save(self, *args, **kwargs):
        self.word_count = self._get_word_count()
        super().save(*args, **kwargs)
        
class BlogContributor(models.Model):
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contribution = models.CharField(max_length=255, blank=True)

    class Meta:
        """
        Nous avons défini l'attribut   unique_together  dans la classe   Meta  pour garantir 
        qu'il n'y a qu'une seule instance de  BlogContributor  pour chaque paire   
        contributor  -   blog
        """
        unique_together = ('contributor', 'blog')

templates/base.html
{% load static %}
<html>
    <head>
        <title>Blog</title>
        <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    </head>
    <body>
        {% comment %} <h1>Blog</h1>
        {% block content %}{% endblock content %}
        {%  if user.is_authenticated %}
            <p><a href="{% url 'blog:home' %}">Accueil</a></p>
            <p>Vous êtes connecté en tant que {{ request.user }}.<a href="{% url 'authentification:logout' %}">Se déconnecter</a>
            </p><a href="{% url 'authentification:password_change' %}">Changer son mot de passe</a></p>
            {% if perms.blog.add_photo %}
                <p><a href="{% url 'blog:photo_upload' %}">Téléverser une photo</a></p>
            {% endif %}
            <p><a href="{% url 'blog:follow_users' %}">Suivre des utilisateurs</a></p>
            <p><a href="{% url 'blog:create_upload_multiple' %}">Télécharger plusieurs photos</a></p>
            <p><a href="{% url 'blog:blog_post' %}">Ecrire un billet</a></p>
        {% endif %} {% endcomment %}
        <div class="sidebar">
            <h1>Blog Photos</h1>
            {% if user.is_authenticated %}
                <p>Salut, {{ user }} !</p>
                {% if user.profile_photo %}
                    <img class="avatar" src={{ user.profile_photo.url }}>
                {% else %}
                    <img class="avatar" src="{% static 'images/default_profile.png'%}">
                {% endif %}
                <p><a href="{% url 'blog:home' %}">Accueil</a></p>

                <p><a href="{% url 'blog:blog_post' %}">Ecrire un billet</a></p>

                {% if perms.blog.add_photo %}
                    <p><a href="{% url 'blog:photo_upload' %}">Téléverser une photo</a></p>
                {% endif %}
                <p><a href="{% url 'blog:create_upload_multiple' %}">Téléverser plusieurs photos</a></p>
                <p><a href="{% url 'blog:follow_users' %}">Suivre des utilisateurs</a></p>
                {% comment %} <p><a href="{% url 'upload_profile_photo' %}">Changer la photo de profil</a></p> {% endcomment %}
                </p><a href="{% url 'authentification:password_change' %}">Changer son mot de passe</a></p>
                <p><a href="{% url 'authentification:logout' %}">Se déconnecter</a></p>
            {% endif %}
        </div>
        <div class="main">
            {% block content %}{% endblock content %}
        </div>
    </body>
</html>